version: "3"

services:
  web: &basePy
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./main:/main
    env_file:
      - ./.envs/.web
    links:
      - mongodb
    restart: unless-stopped
    command: sh /run_web.sh

  # jupyter:
  #   <<: *basePy
  #   ports:
  #     - "8888:8888"
  #   command: sh /run_jupyter.sh
  #   restart: unless-stopped

  mongodb:
    image: mongo:4.0.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mgdata:/var/lib/mongodb/data/
    restart: unless-stopped

  traefik:
    build:
      context: .
      dockerfile: ./containers/traefik/Dockerfile
    depends_on:
      - web
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "1001:1001"
      - "1003:1003"

volumes:
  mgdata: {}
  production_traefik: {}
