name: Push Container to Heroku

on:
  push:
    branches:
      - heroku

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0
        with:
          email: ${{ secrets.xm14@rice.edu }}
          api_key: ${{ secrets.c4fca83a-0df7-4d9c-9f51-94ee7a685e08 }}
          app_name: ${{ secrets.deepface-app1 }}
          dockerfile: "heroku"
